import { AtemState } from 'atem-connection'

export const Legacy2MEState: AtemState = {
	info: {
		apiVersion: 131102,
		model: 3,
		superSources: [
			{
				boxCount: 4,
			},
		],
		mixEffects: [
			{
				keyCount: 2,
			},
			{
				keyCount: 2,
			},
		],
		power: [true, false],
		productIdentifier: 'ATEM 2 M/E Production Switcher',
		capabilities: {
			mixEffects: 2,
			sources: 37,
			downstreamKeyers: 2,
			auxilliaries: 6,
			mixMinusOutputs: 0,
			mediaPlayers: 2,
			serialPorts: 1,
			maxHyperdecks: 4,
			DVEs: 1,
			stingers: 1,
			superSources: 1,
			talkbackChannels: 0,
			cameraControl: true,
			advancedChromaKeyers: false,
			onlyConfigurableOutputs: false,
		},
		multiviewer: {
			count: 2,
			windowCount: 1,
		},
		mediaPool: {
			stillCount: 32,
			clipCount: 2,
		},
		audioMixer: {
			inputs: 19,
			monitors: 1,
			headphones: 0,
		},
		macroPool: {
			macroCount: 100,
		},
	},
	video: {
		mixEffects: [
			{
				index: 0,
				programInput: 1,
				previewInput: 6,
				transitionPreview: false,
				transitionPosition: {
					inTransition: false,
					remainingFrames: 25,
					handlePosition: 0,
				},
				transitionProperties: {
					style: 0,
					selection: [1],
					nextStyle: 0,
					nextSelection: [1],
				},
				transitionSettings: {
					mix: {
						rate: 25,
					},
					dip: {
						rate: 25,
						input: 0,
					},
					wipe: {
						rate: 25,
						pattern: 1,
						borderWidth: 0,
						borderInput: 0,
						symmetry: 5000,
						borderSoftness: 0,
						xPosition: 5000,
						yPosition: 5000,
						reverseDirection: false,
						flipFlop: false,
					},
					DVE: {
						rate: 25,
						logoRate: 25,
						style: 27,
						fillSource: 0,
						keySource: 0,
						enableKey: false,
						preMultiplied: false,
						clip: 0,
						gain: 0,
						invertKey: false,
						reverse: false,
						flipFlop: false,
					},
					stinger: {
						source: 1,
						preMultipliedKey: false,
						clip: 0,
						gain: 0,
						invert: false,
						preroll: 0,
						clipDuration: 25,
						triggerPoint: 13,
						mixRate: 1,
					},
				},
				upstreamKeyers: [
					{
						canFlyKey: true,
						upstreamKeyerId: 0,
						mixEffectKeyType: 0,
						cutSource: 0,
						fillSource: 0,
						onAir: false,
						flyEnabled: false,
						flyKeyframes: [
							{
								keyFrameId: 1,
								sizeX: 1000,
								sizeY: 1000,
								positionX: 0,
								positionY: 0,
								rotation: 0,
								borderOuterWidth: 0,
								borderInnerWidth: 0,
								borderOuterSoftness: 0,
								borderInnerSoftness: 0,
								borderBevelSoftness: 0,
								borderBevelPosition: 0,
								borderOpacity: 0,
								borderHue: 0,
								borderSaturation: 0,
								borderLuma: 1000,
								lightSourceDirection: 360,
								lightSourceAltitude: 25,
								maskTop: 0,
								maskBottom: 0,
								maskLeft: 0,
								maskRight: 0,
							},
							{
								keyFrameId: 2,
								sizeX: 1000,
								sizeY: 1000,
								positionX: 0,
								positionY: 0,
								rotation: 0,
								borderOuterWidth: 0,
								borderInnerWidth: 0,
								borderOuterSoftness: 0,
								borderInnerSoftness: 0,
								borderBevelSoftness: 0,
								borderBevelPosition: 0,
								borderOpacity: 0,
								borderHue: 0,
								borderSaturation: 0,
								borderLuma: 1000,
								lightSourceDirection: 360,
								lightSourceAltitude: 25,
								maskTop: 0,
								maskBottom: 0,
								maskLeft: 0,
								maskRight: 0,
							},
						],
						maskSettings: {
							maskEnabled: false,
							maskTop: 0,
							maskBottom: 0,
							maskLeft: 0,
							maskRight: 0,
						},
						lumaSettings: {
							preMultiplied: false,
							clip: 0,
							gain: 0,
							invert: false,
						},
						chromaSettings: {
							hue: 0,
							gain: 0,
							ySuppress: 0,
							lift: 0,
							narrow: false,
						},
						patternSettings: {
							style: 0,
							size: 0,
							symmetry: 5000,
							softness: 0,
							positionX: 500,
							positionY: 500,
							invert: false,
						},
						dveSettings: {
							sizeX: 0,
							sizeY: 0,
							positionX: 0,
							positionY: 0,
							rotation: 0,
							borderEnabled: false,
							shadowEnabled: false,
							borderBevel: 0,
							borderOuterWidth: 0,
							borderInnerWidth: 0,
							borderOuterSoftness: 0,
							borderInnerSoftness: 0,
							borderBevelSoftness: 0,
							borderBevelPosition: 0,
							borderOpacity: 0,
							borderHue: 0,
							borderSaturation: 0,
							borderLuma: 0,
							lightSourceDirection: 0,
							lightSourceAltitude: 0,
							maskEnabled: false,
							maskTop: 0,
							maskBottom: 0,
							maskLeft: 0,
							maskRight: 0,
							rate: 1,
						},
						flyProperties: {
							isASet: false,
							isBSet: false,
							isAtKeyFrame: 0,
							runToInfiniteIndex: 0,
						},
					},
					{
						canFlyKey: true,
						upstreamKeyerId: 1,
						mixEffectKeyType: 0,
						cutSource: 14,
						fillSource: 13,
						onAir: false,
						flyEnabled: false,
						flyKeyframes: [
							{
								keyFrameId: 1,
								sizeX: 1000,
								sizeY: 1000,
								positionX: 0,
								positionY: 0,
								rotation: 0,
								borderOuterWidth: 0,
								borderInnerWidth: 0,
								borderOuterSoftness: 0,
								borderInnerSoftness: 0,
								borderBevelSoftness: 0,
								borderBevelPosition: 0,
								borderOpacity: 0,
								borderHue: 0,
								borderSaturation: 0,
								borderLuma: 1000,
								lightSourceDirection: 360,
								lightSourceAltitude: 25,
								maskTop: 0,
								maskBottom: 0,
								maskLeft: 0,
								maskRight: 0,
							},
							{
								keyFrameId: 2,
								sizeX: 1000,
								sizeY: 1000,
								positionX: 0,
								positionY: 0,
								rotation: 0,
								borderOuterWidth: 0,
								borderInnerWidth: 0,
								borderOuterSoftness: 0,
								borderInnerSoftness: 0,
								borderBevelSoftness: 0,
								borderBevelPosition: 0,
								borderOpacity: 0,
								borderHue: 0,
								borderSaturation: 0,
								borderLuma: 1000,
								lightSourceDirection: 360,
								lightSourceAltitude: 25,
								maskTop: 0,
								maskBottom: 0,
								maskLeft: 0,
								maskRight: 0,
							},
						],
						maskSettings: {
							maskEnabled: false,
							maskTop: 0,
							maskBottom: 0,
							maskLeft: 0,
							maskRight: 0,
						},
						lumaSettings: {
							preMultiplied: true,
							clip: 0,
							gain: 0,
							invert: false,
						},
						chromaSettings: {
							hue: 0,
							gain: 0,
							ySuppress: 0,
							lift: 0,
							narrow: false,
						},
						patternSettings: {
							style: 0,
							size: 0,
							symmetry: 5000,
							softness: 0,
							positionX: 500,
							positionY: 500,
							invert: false,
						},
						dveSettings: {
							sizeX: 0,
							sizeY: 0,
							positionX: 0,
							positionY: 0,
							rotation: 0,
							borderEnabled: false,
							shadowEnabled: false,
							borderBevel: 0,
							borderOuterWidth: 0,
							borderInnerWidth: 0,
							borderOuterSoftness: 0,
							borderInnerSoftness: 0,
							borderBevelSoftness: 0,
							borderBevelPosition: 0,
							borderOpacity: 0,
							borderHue: 0,
							borderSaturation: 0,
							borderLuma: 0,
							lightSourceDirection: 0,
							lightSourceAltitude: 0,
							maskEnabled: false,
							maskTop: 0,
							maskBottom: 0,
							maskLeft: 0,
							maskRight: 0,
							rate: 1,
						},
						flyProperties: {
							isASet: false,
							isBSet: false,
							isAtKeyFrame: 0,
							runToInfiniteIndex: 0,
						},
					},
				],
				fadeToBlack: {
					rate: 25,
					isFullyBlack: false,
					inTransition: false,
					remainingFrames: 25,
				},
			},
			{
				index: 1,
				programInput: 2,
				previewInput: 5,
				transitionPreview: false,
				transitionPosition: {
					inTransition: false,
					remainingFrames: 6,
					handlePosition: 0,
				},
				transitionProperties: {
					style: 0,
					selection: [1],
					nextStyle: 0,
					nextSelection: [1],
				},
				transitionSettings: {
					mix: {
						rate: 6,
					},
					dip: {
						rate: 25,
						input: 0,
					},
					wipe: {
						rate: 25,
						pattern: 1,
						borderWidth: 0,
						borderInput: 0,
						symmetry: 5000,
						borderSoftness: 0,
						xPosition: 5000,
						yPosition: 5000,
						reverseDirection: false,
						flipFlop: false,
					},
					DVE: {
						rate: 25,
						logoRate: 25,
						style: 27,
						fillSource: 0,
						keySource: 0,
						enableKey: false,
						preMultiplied: false,
						clip: 0,
						gain: 0,
						invertKey: false,
						reverse: false,
						flipFlop: false,
					},
					stinger: {
						source: 1,
						preMultipliedKey: false,
						clip: 0,
						gain: 0,
						invert: false,
						preroll: 0,
						clipDuration: 25,
						triggerPoint: 13,
						mixRate: 1,
					},
				},
				upstreamKeyers: [
					{
						canFlyKey: true,
						upstreamKeyerId: 0,
						mixEffectKeyType: 0,
						cutSource: 0,
						fillSource: 0,
						onAir: false,
						flyEnabled: false,
						flyKeyframes: [
							{
								keyFrameId: 1,
								sizeX: 1000,
								sizeY: 1000,
								positionX: 0,
								positionY: 0,
								rotation: 0,
								borderOuterWidth: 0,
								borderInnerWidth: 0,
								borderOuterSoftness: 0,
								borderInnerSoftness: 0,
								borderBevelSoftness: 0,
								borderBevelPosition: 0,
								borderOpacity: 0,
								borderHue: 0,
								borderSaturation: 0,
								borderLuma: 1000,
								lightSourceDirection: 360,
								lightSourceAltitude: 25,
								maskTop: 0,
								maskBottom: 0,
								maskLeft: 0,
								maskRight: 0,
							},
							{
								keyFrameId: 2,
								sizeX: 1000,
								sizeY: 1000,
								positionX: 0,
								positionY: 0,
								rotation: 0,
								borderOuterWidth: 0,
								borderInnerWidth: 0,
								borderOuterSoftness: 0,
								borderInnerSoftness: 0,
								borderBevelSoftness: 0,
								borderBevelPosition: 0,
								borderOpacity: 0,
								borderHue: 0,
								borderSaturation: 0,
								borderLuma: 1000,
								lightSourceDirection: 360,
								lightSourceAltitude: 25,
								maskTop: 0,
								maskBottom: 0,
								maskLeft: 0,
								maskRight: 0,
							},
						],
						maskSettings: {
							maskEnabled: false,
							maskTop: 0,
							maskBottom: 0,
							maskLeft: 0,
							maskRight: 0,
						},
						lumaSettings: {
							preMultiplied: false,
							clip: 0,
							gain: 0,
							invert: false,
						},
						chromaSettings: {
							hue: 0,
							gain: 0,
							ySuppress: 0,
							lift: 0,
							narrow: false,
						},
						patternSettings: {
							style: 0,
							size: 0,
							symmetry: 5000,
							softness: 0,
							positionX: 500,
							positionY: 500,
							invert: false,
						},
						dveSettings: {
							sizeX: 0,
							sizeY: 0,
							positionX: 0,
							positionY: 0,
							rotation: 0,
							borderEnabled: false,
							shadowEnabled: false,
							borderBevel: 0,
							borderOuterWidth: 0,
							borderInnerWidth: 0,
							borderOuterSoftness: 0,
							borderInnerSoftness: 0,
							borderBevelSoftness: 0,
							borderBevelPosition: 0,
							borderOpacity: 0,
							borderHue: 0,
							borderSaturation: 0,
							borderLuma: 0,
							lightSourceDirection: 0,
							lightSourceAltitude: 0,
							maskEnabled: false,
							maskTop: 0,
							maskBottom: 0,
							maskLeft: 0,
							maskRight: 0,
							rate: 1,
						},
						flyProperties: {
							isASet: false,
							isBSet: false,
							isAtKeyFrame: 0,
							runToInfiniteIndex: 144,
						},
					},
					{
						canFlyKey: true,
						upstreamKeyerId: 1,
						mixEffectKeyType: 0,
						cutSource: 0,
						fillSource: 0,
						onAir: false,
						flyEnabled: false,
						flyKeyframes: [
							{
								keyFrameId: 1,
								sizeX: 1000,
								sizeY: 1000,
								positionX: 0,
								positionY: 0,
								rotation: 0,
								borderOuterWidth: 0,
								borderInnerWidth: 0,
								borderOuterSoftness: 0,
								borderInnerSoftness: 0,
								borderBevelSoftness: 0,
								borderBevelPosition: 0,
								borderOpacity: 0,
								borderHue: 0,
								borderSaturation: 0,
								borderLuma: 1000,
								lightSourceDirection: 360,
								lightSourceAltitude: 25,
								maskTop: 0,
								maskBottom: 0,
								maskLeft: 0,
								maskRight: 0,
							},
							{
								keyFrameId: 2,
								sizeX: 1000,
								sizeY: 1000,
								positionX: 0,
								positionY: 0,
								rotation: 0,
								borderOuterWidth: 0,
								borderInnerWidth: 0,
								borderOuterSoftness: 0,
								borderInnerSoftness: 0,
								borderBevelSoftness: 0,
								borderBevelPosition: 0,
								borderOpacity: 0,
								borderHue: 0,
								borderSaturation: 0,
								borderLuma: 1000,
								lightSourceDirection: 360,
								lightSourceAltitude: 25,
								maskTop: 0,
								maskBottom: 0,
								maskLeft: 0,
								maskRight: 0,
							},
						],
						maskSettings: {
							maskEnabled: false,
							maskTop: 0,
							maskBottom: 0,
							maskLeft: 0,
							maskRight: 0,
						},
						lumaSettings: {
							preMultiplied: false,
							clip: 0,
							gain: 0,
							invert: false,
						},
						chromaSettings: {
							hue: 0,
							gain: 0,
							ySuppress: 0,
							lift: 0,
							narrow: false,
						},
						patternSettings: {
							style: 0,
							size: 0,
							symmetry: 5000,
							softness: 0,
							positionX: 500,
							positionY: 500,
							invert: false,
						},
						dveSettings: {
							sizeX: 0,
							sizeY: 0,
							positionX: 0,
							positionY: 0,
							rotation: 0,
							borderEnabled: false,
							shadowEnabled: false,
							borderBevel: 0,
							borderOuterWidth: 0,
							borderInnerWidth: 0,
							borderOuterSoftness: 0,
							borderInnerSoftness: 0,
							borderBevelSoftness: 0,
							borderBevelPosition: 0,
							borderOpacity: 0,
							borderHue: 0,
							borderSaturation: 0,
							borderLuma: 0,
							lightSourceDirection: 0,
							lightSourceAltitude: 0,
							maskEnabled: false,
							maskTop: 0,
							maskBottom: 0,
							maskLeft: 0,
							maskRight: 0,
							rate: 1,
						},
						flyProperties: {
							isASet: false,
							isBSet: false,
							isAtKeyFrame: 0,
							runToInfiniteIndex: 76,
						},
					},
				],
				fadeToBlack: {
					rate: 25,
					isFullyBlack: false,
					inTransition: false,
					remainingFrames: 25,
				},
			},
		],
		downstreamKeyers: [
			{
				isAuto: false,
				remainingFrames: 25,
				onAir: false,
				inTransition: false,
				sources: {
					fillSource: 16,
					cutSource: 15,
				},
				properties: {
					tie: false,
					rate: 25,
					preMultiply: true,
					clip: 0,
					gain: 0,
					invert: false,
					mask: {
						enabled: false,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
					},
				},
				isTowardsOnAir: true,
			},
			{
				isAuto: false,
				remainingFrames: 25,
				onAir: false,
				inTransition: false,
				sources: {
					fillSource: 13,
					cutSource: 14,
				},
				properties: {
					tie: false,
					rate: 25,
					preMultiply: true,
					clip: 0,
					gain: 0,
					invert: false,
					mask: {
						enabled: false,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
					},
				},
				isTowardsOnAir: true,
			},
		],
		auxilliaries: [10010, 10020, 6000, 0, 10, 7001],
		superSources: [
			{
				index: 0,
				boxes: [
					{
						enabled: true,
						source: 1,
						x: -800,
						y: 50,
						size: 580,
						cropped: true,
						cropTop: 0,
						cropBottom: 0,
						cropLeft: 0,
						cropRight: 2000,
					},
					{
						enabled: true,
						source: 2001,
						x: 800,
						y: 50,
						size: 580,
						cropped: false,
						cropTop: 0,
						cropBottom: 0,
						cropLeft: 0,
						cropRight: 0,
					},
					{
						enabled: false,
						source: 0,
						x: 0,
						y: 0,
						size: 1000,
						cropped: false,
						cropTop: 0,
						cropBottom: 0,
						cropLeft: 0,
						cropRight: 0,
					},
					{
						enabled: false,
						source: 0,
						x: 0,
						y: 0,
						size: 1000,
						cropped: false,
						cropTop: 0,
						cropBottom: 0,
						cropLeft: 0,
						cropRight: 0,
					},
				],
				properties: {
					artFillSource: 3010,
					artCutSource: 3011,
					artOption: 1,
					artPreMultiplied: true,
					artClip: 0,
					artGain: 0,
					artInvertKey: false,
				},
				border: {
					borderEnabled: false,
					borderBevel: 0,
					borderOuterWidth: 0,
					borderInnerWidth: 0,
					borderOuterSoftness: 0,
					borderInnerSoftness: 0,
					borderBevelSoftness: 0,
					borderBevelPosition: 0,
					borderHue: 0,
					borderSaturation: 0,
					borderLuma: 0,
					borderLightSourceDirection: 0,
					borderLightSourceAltitude: 10,
				},
			},
		],
	},
	media: {
		stillPool: [
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
			{
				isUsed: false,
				hash: 'AAAAAAAAAAAAAAAAAAAAAA==',
				fileName: '',
			},
		],
		clipPool: [
			{
				isUsed: false,
				name: '',
				frameCount: 0,
				frames: [],
			},
			{
				isUsed: false,
				name: '',
				frameCount: 0,
				frames: [],
			},
		],
		players: [
			{
				playing: false,
				loop: false,
				atBeginning: true,
				clipFrame: 0,
				sourceType: 1,
				clipIndex: 0,
				stillIndex: 0,
			},
			{
				playing: false,
				loop: false,
				atBeginning: true,
				clipFrame: 0,
				sourceType: 1,
				clipIndex: 1,
				stillIndex: 1,
			},
		],
	},
	inputs: {
		'0': {
			inputId: 0,
			longName: 'Black',
			shortName: 'BLK',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 1,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'1': {
			inputId: 1,
			longName: 'Camera 1',
			shortName: 'Cam1',
			areNamesDefault: false,
			externalPorts: [1, 2],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'2': {
			inputId: 2,
			longName: 'Camera 2',
			shortName: 'Cam2',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'3': {
			inputId: 3,
			longName: 'Camera 3',
			shortName: 'Cam3',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'4': {
			inputId: 4,
			longName: 'Camera 4',
			shortName: 'Cam4',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'5': {
			inputId: 5,
			longName: 'Camera 5',
			shortName: 'Cam5',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'6': {
			inputId: 6,
			longName: 'Presenter',
			shortName: 'Pres',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'7': {
			inputId: 7,
			longName: 'MP3B (Studio2)',
			shortName: 'MP2B',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'8': {
			inputId: 8,
			longName: 'SuperSource 2',
			shortName: 'SS 2',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'9': {
			inputId: 9,
			longName: 'MP1 Next',
			shortName: 'MP1N',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'10': {
			inputId: 10,
			longName: 'MP3 (Studio)',
			shortName: 'MP3',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'11': {
			inputId: 11,
			longName: 'MP1 (Clip)',
			shortName: 'MP1',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'12': {
			inputId: 12,
			longName: 'MP2 (Grafikk)',
			shortName: 'MP2',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'13': {
			inputId: 13,
			longName: 'DSK2K',
			shortName: 'DK2K',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'14': {
			inputId: 14,
			longName: 'DSK2F',
			shortName: 'DK2F',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'15': {
			inputId: 15,
			longName: 'DSK1K',
			shortName: 'DK1K',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'16': {
			inputId: 16,
			longName: 'DSK1F',
			shortName: 'DK1F',
			areNamesDefault: false,
			externalPorts: [1],
			externalPortType: 1,
			internalPortType: 0,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'1000': {
			inputId: 1000,
			longName: 'Color Bars',
			shortName: 'BARS',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 2,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'2001': {
			inputId: 2001,
			longName: 'Color 1',
			shortName: 'COL1',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 3,
			sourceAvailability: 15,
			meAvailability: 3,
		},
		'2002': {
			inputId: 2002,
			longName: 'Color 2',
			shortName: 'COL2',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 3,
			sourceAvailability: 15,
			meAvailability: 3,
		},
		'3010': {
			inputId: 3010,
			longName: 'Media Player 1',
			shortName: 'MP1',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 4,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'3011': {
			inputId: 3011,
			longName: 'Media Player 1 Key',
			shortName: 'MP1K',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 5,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'3020': {
			inputId: 3020,
			longName: 'Media Player 2',
			shortName: 'MP2',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 4,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'3021': {
			inputId: 3021,
			longName: 'Media Player 2 Key',
			shortName: 'MP2K',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 5,
			sourceAvailability: 31,
			meAvailability: 3,
		},
		'6000': {
			inputId: 6000,
			longName: 'SuperSource',
			shortName: 'SSRC',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 6,
			sourceAvailability: 27,
			meAvailability: 3,
		},
		'7001': {
			inputId: 7001,
			longName: 'Clean Feed 1',
			shortName: 'CFD1',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 128,
			sourceAvailability: 3,
			meAvailability: 0,
		},
		'7002': {
			inputId: 7002,
			longName: 'Clean Feed 2',
			shortName: 'CFD2',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 128,
			sourceAvailability: 3,
			meAvailability: 0,
		},
		'8001': {
			inputId: 8001,
			longName: 'A1 error',
			shortName: 'Aux1',
			areNamesDefault: false,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 129,
			sourceAvailability: 2,
			meAvailability: 0,
		},
		'8002': {
			inputId: 8002,
			longName: 'Auxiliary 2',
			shortName: 'AUX2',
			areNamesDefault: true,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 129,
			sourceAvailability: 2,
			meAvailability: 0,
		},
		'8003': {
			inputId: 8003,
			longName: 'A3 supersource',
			shortName: 'Aux3',
			areNamesDefault: false,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 129,
			sourceAvailability: 2,
			meAvailability: 0,
		},
		'8004': {
			inputId: 8004,
			longName: 'Auxiliary 4',
			shortName: 'Aux4',
			areNamesDefault: false,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 129,
			sourceAvailability: 2,
			meAvailability: 0,
		},
		'8005': {
			inputId: 8005,
			longName: 'A5 Lookahead',
			shortName: 'Aux5',
			areNamesDefault: false,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 129,
			sourceAvailability: 2,
			meAvailability: 0,
		},
		'8006': {
			inputId: 8006,
			longName: 'A6 Clean',
			shortName: 'Aux6',
			areNamesDefault: false,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 129,
			sourceAvailability: 2,
			meAvailability: 0,
		},
		'10010': {
			inputId: 10010,
			longName: 'ME1 Program',
			shortName: 'M/E1',
			areNamesDefault: false,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 128,
			sourceAvailability: 3,
			meAvailability: 0,
		},
		'10011': {
			inputId: 10011,
			longName: 'ME1 Preview2',
			shortName: 'Pvw1',
			areNamesDefault: false,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 128,
			sourceAvailability: 3,
			meAvailability: 0,
		},
		'10020': {
			inputId: 10020,
			longName: 'ME2 Program',
			shortName: 'M/E2',
			areNamesDefault: false,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 128,
			sourceAvailability: 11,
			meAvailability: 1,
		},
		'10021': {
			inputId: 10021,
			longName: 'ME2 Preview',
			shortName: 'Pvw2',
			areNamesDefault: false,
			externalPorts: [256],
			externalPortType: 256,
			internalPortType: 128,
			sourceAvailability: 11,
			meAvailability: 1,
		},
	},
	macro: {
		macroPlayer: {
			isRunning: false,
			isWaiting: false,
			loop: false,
			macroIndex: 65535,
		},
		macroRecorder: {
			isRecording: false,
			macroIndex: 0,
		},
		macroProperties: [
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'sdf',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'dummy',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'lib-dummy',
				description: 'd2',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'Sinder',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'settings',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'z',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'dev1',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'dev2',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'dummy',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'color',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'ftb',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'dsk props',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'chroma1',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'dve-altitude',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'dve-alt2',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'trans wipe and dip',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'Enter HEL',
				description: 'Tween into HEL',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'Exit HEL',
				description: 'Tween out of HEL',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'xplosion-test',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'test2',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'another macro',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'me2 auto loop',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'fake an implosion',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'end of the line',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: true,
				hasUnsupportedOps: false,
				name: 'media',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
			{
				isUsed: false,
				hasUnsupportedOps: false,
				name: '',
				description: '',
			},
		],
	},
	settings: {
		multiViewers: [
			{
				index: 0,
				windows: [
					{
						windowIndex: 0,
						source: 10011,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 1,
						source: 10010,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 2,
						source: 11,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 3,
						source: 9,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 4,
						source: 12,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 5,
						source: 10,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 6,
						source: 16,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 7,
						source: 15,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 8,
						source: 14,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 9,
						source: 13,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
				],
				properties: {
					layout: 12,
					programPreviewSwapped: false,
				},
			},
			{
				index: 1,
				windows: [
					{
						windowIndex: 0,
						source: 10021,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 1,
						source: 10020,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 2,
						source: 8001,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 3,
						source: 8003,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 4,
						source: 8005,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 5,
						source: 8006,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 6,
						source: 7,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 7,
						source: 8,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 8,
						source: 6,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
					{
						windowIndex: 9,
						source: 1,
						supportsVuMeter: false,
						supportsSafeArea: false,
					},
				],
				properties: {
					layout: 12,
					programPreviewSwapped: false,
				},
			},
		],
		videoMode: 6,
	},
	audio: {
		numberOfChannels: 19,
		hasMonitor: true,
		channels: [
			undefined,
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 0,
				portType: 1,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{
				sourceType: 2,
				portType: 32,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{
				sourceType: 1,
				portType: 256,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
			{
				sourceType: 1,
				portType: 256,
				mixOption: 0,
				gain: 0,
				balance: 0,
				supportsRcaToXlrEnabled: false,
				rcaToXlrEnabled: false,
			},
		],
		audioFollowVideoCrossfadeTransitionEnabled: true,
		master: {
			gain: 0,
			balance: 0,
			followFadeToBlack: false,
		},
		monitor: {
			enabled: false,
			gain: 0,
			mute: false,
			solo: false,
			soloSource: 1,
			dim: false,
			dimLevel: 2000,
		},
	},
	colorGenerators: {
		'0': {
			hue: 500,
			saturation: 1000,
			luma: 500,
		},
		'1': {
			hue: 270,
			saturation: 1000,
			luma: 500,
		},
	},
}
